### ISSUE TITLE
Примеры настроек

### ISSUE THREAD

**Issue by popoffvg** [Stepa86/1C-Deploy-and-CopyDB#3]
Добрый день!
Не могли бы обновить примеры настроек, т.к. вроде как в файле import.json должны указываться настройки подключения к базе, но в примере данные настройки отсутствуют

**Comment by Stepa86** [comment]
@Suricatt 
Параметры читаются из переменных окружения, из переданных на вход файлов и из файла param_os.json 

Команда в файле https://github.com/Stepa86/1C-Deploy-and-CopyDB/blob/master/bin/PC/BaseName/import.bat читает сперва настройки из файла по умолчанию https://github.com/Stepa86/1C-Deploy-and-CopyDB/blob/master/bin/PC/BaseName/param_os.json . Он не указан в строке запуска, но все равно читается по умолчанию (всегда пытается прочитаться файл param_os.json рядом со скриптом). В этом файле указан список файлов для чтения различных настроек. Последним идет файл  https://github.com/Stepa86/1C-Deploy-and-CopyDB/blob/master/bin/PC/BaseName/base.json где и указаны параметры базы для импорта

Затем читается переданный файл https://github.com/Stepa86/1C-Deploy-and-CopyDB/blob/master/bin/PC/BaseName/import.json с подменой ранее загруженных параметров - в нем указывается где будет лежать файл бекапа, каким скриптом прогружать и имя базы из которой грузить. 

Так же все параметры можно переопределить через переменные окружения, например вот так подменяются параметры слаки и отключается подключение к хранилищу

```
set slack_WebhookURL=https://hooks.slack.com/services/...
set slack_StartMessage=:ghost: *import UPP*
set slack_channel=@Stepa86
set Repo.Blind=false
..\..\..\oscript\bin\oscript.exe ..\..\..\src\CopyBase.os import.json
```

**Comment by popoffvg** [comment]
Спасибо большое за подробный ответ!
